esphome:
  name: esp32c3-presence
  friendly_name: ESP32C3 Presence Node

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# USB logging disabled UART usage
logger:
  baud_rate: 115200

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# --------------------
# I2C for VEML7700
# --------------------
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 100kHz

# ====================
# SENSORS
# ====================
sensor:
  # VEML7700
  - platform: veml7700
    address: 0x10
    update_interval: 30s

    ambient_light:
      name: "Ambient Light (Lux)"

    full_spectrum:
      name: "Full Spectrum Light"

    infrared:
      name: "Infrared Light"

    actual_gain:
      name: "VEML7700 Gain"

    actual_integration_time:
      name: "VEML7700 Integration Time"


# ====================
# BINARY SENSORS
# ====================
binary_sensor:
  # Presence via LD2420 D-OUT pin
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT
    name: "Radar Presence"
    device_class: occupancy

  # Push button
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Push Button"
    on_press:
      then:
        - light.toggle: status_pixels

# --------------------
# Neopixels (5 LEDs)
# --------------------
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO6
    num_leds: 5
    name: "Status Neopixels"
    id: status_pixels
    restore_mode: "RESTORE_DEFAULT_OFF"
