esphome:
  name: presence_node_${device_id}
  friendly_name: PresenceNode_${device_id}
  includes:
    - led_engine.h
  platformio_options:
    lib_deps:
      - makuna/NeoPixelBus @ ^2.7.0
  on_boot:
    priority: 600
    then:
      - lambda: |-
          led_engine_setup();
          start_boot_animation();


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# USB logging disabled UART usage
logger:
  baud_rate: 115200

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


interval:
  - interval: 16ms
    then:
      - lambda: |-
          led_engine_loop();


# --------------------
# I2C for VEML7700
# --------------------
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 100kHz

# ====================
# EVENT ENTITY (The "Commercial" Feature)
# ====================
event:
  - platform: template
    name: "Button"
    id: button_event
    device_class: button
    # These are the specific event types HA will recognize
    event_types:
      - single_press
      - double_press
      - long_press

# ====================
# SENSORS
# ====================
sensor:
  # VEML7700
  - platform: veml7700
    address: 0x10
    update_interval: 30s

    ambient_light:
      name: "Ambient Light (Lux)"

    full_spectrum:
      name: "Full Spectrum Light"

    infrared:
      name: "Infrared Light"

    actual_gain:
      name: "VEML7700 Gain"

    actual_integration_time:
      name: "VEML7700 Integration Time"


# ====================
# BINARY SENSORS
# ====================
binary_sensor:
  # Presence via LD2420 D-OUT pin
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT
    name: "Radar Presence"
    device_class: occupancy

  # Push button with multi-click support
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Push Button"
    # Internal: true hides the raw "On/Off" state from HA so you only see the Events
    internal: true
    
    on_multi_click:
      # Single Click
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 200ms
        then:
          - event.trigger:
              id: button_event
              event_type: single_press
          - lambda: |-
              start_center_pulse();
          - logger.log: "Event Fired: Single Press"

      # Double Click
      - timing:
          - ON for 50ms to 350ms
          - OFF for 50ms to 350ms
          - ON for 50ms to 350ms
        then:
          - event.trigger:
              id: button_event
              event_type: double_press
          - lambda: |-
              start_center_pulse_double_press();
          - logger.log: "Event Fired: Double Press"

      # Long Press
      - timing:
          - ON for at least 500ms
        then:
          - event.trigger:
              id: button_event
              event_type: long_press
          - lambda: |-
              start_center_pulse_long_press();
          - logger.log: "Event Fired: Long Press"
