esphome:
  name: presence_node_${device_id}
  friendly_name: PresenceNode_${device_id}
  includes:
    - led_engine.h
  platformio_options:
    lib_deps:
      - makuna/NeoPixelBus @ ^2.7.0
  on_boot:
    priority: 600
    then:
      - globals.set: { id: motion_enabled, value: 'true' }
      - lambda: |-
          led_engine_setup();
          start_boot_animation();

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  baud_rate: 115200

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "PresenceNode_${device_id}_Setup"
    password: ""

captive_portal:

globals:
  - id: motion_enabled
    type: bool
    restore_value: no
    initial_value: 'true'

interval:
  - interval: 16ms
    then:
      - lambda: |-
          led_engine_loop();

# --------------------
# I2C
# --------------------
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 100kHz

# ====================
# EVENT ENTITY
# ====================
event:
  - platform: template
    name: "Button"
    id: button_event
    device_class: button
    event_types:
      - single_press
      - double_press
      - long_press

# ====================
# LIGHT SENSOR
# ====================
sensor:
  - platform: veml7700
    address: 0x10
    update_interval: 30s
    ambient_light:
      name: "Ambient Light (Lux)"
    full_spectrum:
      name: "Full Spectrum Light"
    infrared:
      name: "Infrared Light"
    actual_gain:
      name: "VEML7700 Gain"
    actual_integration_time:
      name: "VEML7700 Integration Time"

# ====================
# MOTION ENABLE SWITCH (HA)
# ====================
switch:
  - platform: template
    name: "Motion Enabled"
    id: motion_enabled_switch
    lambda: |-
      return id(motion_enabled);
    turn_on_action:
      - globals.set: { id: motion_enabled, value: 'true' }
    turn_off_action:
      - globals.set: { id: motion_enabled, value: 'false' }
      - binary_sensor.template.publish:
          id: radar_presence
          state: OFF

# ====================
# BINARY SENSORS
# ====================
binary_sensor:
  - platform: template
    id: radar_presence
    name: "Radar Presence"
    device_class: occupancy
    lambda: |-
      return id(motion_enabled) && digitalRead(7);

  # PUSH BUTTON
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    name: "Push Button"

    on_multi_click:

      # SINGLE
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 200ms
        then:
          - event.trigger:
              id: button_event
              event_type: single_press
          - lambda: |-
              start_center_pulse_single_press();
          - logger.log: "Event Fired: Single Press"

      # DOUBLE
      - timing:
          - ON for 50ms to 350ms
          - OFF for 50ms to 350ms
          - ON for 50ms to 350ms
        then:
          - event.trigger:
              id: button_event
              event_type: double_press
          - lambda: |-
              start_center_pulse_double_press();
          - logger.log: "Event Fired: Double Press"

      # LONG  ← YOUR TOGGLE
      - timing:
          - ON for at least 500ms
        then:

          # toggle stored state
          - globals.set:
              id: motion_enabled
              value: !lambda 'return !id(motion_enabled);'

          # if disabled → force radar OFF
          - if:
              condition:
                lambda: 'return !id(motion_enabled);'
              then:
                - binary_sensor.template.publish:
                    id: radar_presence
                    state: OFF

          # fire HA event
          - event.trigger:
              id: button_event
              event_type: long_press

          # LED feedback
          - lambda: |-
              if (id(motion_enabled)) {
                start_center_pulse_long_press();
              } else {
                start_center_pulse_long_press_disabled();
              }

          - logger.log:
              format: "Motion Enabled now: %s"
              args: ['id(motion_enabled) ? "TRUE" : "FALSE"']
