esphome:
  name: presence_node_${device_id}
  friendly_name: PresenceNode_${device_id}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# USB logging disabled UART usage
logger:
  baud_rate: 115200

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# --------------------
# I2C for VEML7700
# --------------------
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 100kHz

# ====================
# SENSORS
# ====================
sensor:
  # VEML7700
  - platform: veml7700
    address: 0x10
    update_interval: 30s

    ambient_light:
      name: "Ambient Light (Lux)"

    full_spectrum:
      name: "Full Spectrum Light"

    infrared:
      name: "Infrared Light"

    actual_gain:
      name: "VEML7700 Gain"

    actual_integration_time:
      name: "VEML7700 Integration Time"


# ====================
# BINARY SENSORS
# ====================
binary_sensor:
  # Presence via LD2420 D-OUT pin
  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT
    name: "Radar Presence"
    device_class: occupancy

  # Push button with multi-click support
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Push Button"
    # on_multi_click is the correct trigger for handling patterns
    on_multi_click:
      # Single Click
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 200ms
        then:
          - logger.log: "Button Single Clicked"

      # Double Click
      - timing:
          - ON for 50ms to 350ms
          - OFF for 50ms to 350ms
          - ON for 50ms to 350ms
        then:
          - logger.log: "Button Double Clicked"

      # Long Press
      - timing:
          - ON for at least 500ms
        then:
          - logger.log: "Button Long Pressed"


# --------------------
# Neopixels (5 LEDs)
# --------------------
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO6
    num_leds: 5
    name: "Integrated NeoPixels"
    id: integrated_neo_pixels
    restore_mode: "RESTORE_DEFAULT_OFF"
