esphome:
  name: presence_node_${device_id}
  friendly_name: PresenceNode_${device_id}
  includes:
    - led_engine.h
  platformio_options:
    lib_deps:
      - makuna/NeoPixelBus @ ^2.7.0
  on_boot:
    priority: 600
    then:
      - globals.set: { id: motion_enabled, value: 'true' }
      - lambda: |-
          led_init();
          led_play_boot();

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  baud_rate: 115200

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "PresenceNode_${device_id}_Setup"
    password: ""

captive_portal:

globals:
  - id: motion_enabled
    type: bool
    restore_value: no
    initial_value: 'true'

interval:
  - interval: 16ms
    then:
      - lambda: |-
          led_tick();

# --------------------
# I2C
# --------------------
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 100kHz

# --------------------
# UART for LD2420
# --------------------
uart:
  id: uart_mmwave
  tx_pin: GPIO4
  rx_pin: GPIO5
  baud_rate: 115200
  parity: NONE
  stop_bits: 1


ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: "LD2420 Firmware Version"

# ====================
# EVENT ENTITY
# ====================
event:
  - platform: template
    name: "Button"
    id: button_event
    device_class: button
    event_types:
      - single_press
      - double_press
      - long_press

# ====================
# LIGHT SENSOR
# ====================
sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
  - platform: veml7700
    address: 0x10
    update_interval: 3s
    ambient_light:
      name: "Ambient Light (Lux)"
    full_spectrum:
      name: "Full Spectrum Light"
    infrared:
      name: "Infrared Light"
    actual_gain:
      name: "VEML7700 Gain"
    actual_integration_time:
      name: "VEML7700 Integration Time"

# ====================
# MOTION ENABLE SWITCH (HA)
# ====================
switch:
  - platform: template
    name: "Motion Enabled"
    id: motion_enabled_switch
    lambda: |-
      return id(motion_enabled);
    turn_on_action:
      - globals.set: { id: motion_enabled, value: 'true' }
      - lambda: |-
          // Optional: LED feedback when motion enabled via HA
          led_play_feedback_motion_on();
    turn_off_action:
      - globals.set: { id: motion_enabled, value: 'false' }
      - binary_sensor.template.publish:
          id: radar_presence
          state: OFF
      - lambda: |-
          // LED feedback when motion disabled via HA
          led_play_feedback_motion_off();


# ====================
# BINARY SENSORS
# ====================
binary_sensor:
  # UART Presence
  - platform: ld2420
    has_target:
      name: Occupancy

  # GPIO Presence
  - platform: template
    id: radar_presence
    name: "Radar Presence"
    device_class: occupancy
    lambda: |-
      return id(motion_enabled) && digitalRead(7);

  # PUSH BUTTON
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    name: "Push Button"

    on_multi_click:

      # SINGLE
      - timing:
          - ON for 50ms to 350ms
          - OFF for at least 200ms
        then:
          - event.trigger:
              id: button_event
              event_type: single_press
          - lambda: |-
              led_play_feedback_single();
          - logger.log: "Event Fired: Single Press"

      # DOUBLE
      - timing:
          - ON for 50ms to 350ms
          - OFF for 50ms to 350ms
          - ON for 50ms to 350ms
        then:
          - event.trigger:
              id: button_event
              event_type: double_press
          - lambda: |-
              led_play_feedback_double();
          - logger.log: "Event Fired: Double Press"

      # LONG  ← YOUR TOGGLE
      - timing:
          - ON for at least 500ms
        then:

          # toggle stored state
          - globals.set:
              id: motion_enabled
              value: !lambda 'return !id(motion_enabled);'

          # if disabled → force radar OFF
          - if:
              condition:
                lambda: 'return !id(motion_enabled);'
              then:
                - binary_sensor.template.publish:
                    id: radar_presence
                    state: OFF

          # fire HA event
          - event.trigger:
              id: button_event
              event_type: long_press

          # LED feedback
          - lambda: |-
              if (id(motion_enabled)) {
                led_play_feedback_motion_on();
              } else {
                led_play_feedback_motion_off();
              }

          - logger.log:
              format: "Motion Enabled now: %s"
              args: ['id(motion_enabled) ? "TRUE" : "FALSE"']

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits