blueprint:
  name: ESPhome Button Light Controller (Multi-Light)
  description: >
    Controls multiple lights using an ESPhome button event.
    Single press toggles lights.
    Double press toggles color temperature between 200 mireds and max.
    (Uses the first selected light as the reference for the current state).
  domain: automation

  input:
    button_entity:
      name: Button Entity
      description: The ESPhome event entity (like event.bedroom_button)
      selector:
        entity:
          domain: event
    light_entities:
      name: Light Entities
      description: The lights to control
      selector:
        entity:
          domain: light
          multiple: true

mode: queued
max: 10

trigger:
  - platform: state
    entity_id: !input button_entity
    # FIX: Ignore triggers caused by the device rebooting/connecting
    not_from:
      - "unavailable"
      - "unknown"

action:
  - choose:
      # SINGLE PRESS -> toggle all lights
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: single_press
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_entities

      # DOUBLE PRESS -> toggle color temperature
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: double_press
        sequence:
          # We import the lights input into a variable named 'lights'
          - variables:
              lights: !input light_entities
          
          - service: light.turn_on
            target:
              entity_id: !input light_entities
            data:
              transition: 1
              color_temp: >
                {# Normalize list #}
                {% set entity_list = lights if lights is iterable and lights is not string else [lights] %}

                {# Keep only ONLINE lights first (critical fix) #}
                {% set online = expand(entity_list)
                  | rejectattr('state','in',['unavailable','unknown'])
                  | map(attribute='entity_id')
                  | list %}

                {# If at least one online light exists #}
                {% if online | length > 0 %}

                  {% set ref = online[0] %}

                  {% set current = state_attr(ref,'color_temp') | int(200) %}
                  {% set min_ct = 200 %}
                  {% set max_ct = [300, state_attr(ref,'max_mireds') | int(370)] | min %}

                  {% if current <= min_ct + 5 %}
                    {{ max_ct }}
                  {% else %}
                    {{ min_ct }}
                  {% endif %}

                {% else %}
                  300
                {% endif %}
