blueprint:
  name: ESPhome Button Light Controller (Multi-Light)
  description: >
    Controls multiple lights using an ESPhome button event.
    Single press toggles lights.
    Double press toggles color temperature between user-defined mired values.
    (Uses the first selected light as the reference for the current state).
  domain: automation

  input:
    button_entity:
      name: Button Entity
      description: The ESPhome event entity (like event.bedroom_button)
      selector:
        entity:
          domain: event

    light_entities:
      name: Light Entities
      description: The lights to control
      selector:
        entity:
          domain: light
          multiple: true

    min_mired:
      name: Warm Color Temp (mired)
      description: Lower mired value (example 200)
      default: 200
      selector:
        number:
          min: 150
          max: 500
          step: 1
          mode: box

    max_mired:
      name: Cool Color Temp (mired)
      description: Upper mired value (example 300)
      default: 300
      selector:
        number:
          min: 150
          max: 500
          step: 1
          mode: box


mode: queued
max: 10

trigger:
  - platform: state
    entity_id: !input button_entity
    not_from:
      - "unavailable"
      - "unknown"

action:
  - choose:

      # SINGLE PRESS -> toggle all lights
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: single_press
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_entities


      # DOUBLE PRESS -> toggle color temperature
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: double_press
        sequence:

          - variables:
              lights: !input light_entities
              min_ct: !input min_mired
              max_ct_user: !input max_mired

          - service: light.turn_on
            target:
              entity_id: !input light_entities
            data:
              transition: 1
              color_temp: >

                {% set entity_list = lights if lights is iterable and lights is not string else [lights] %}

                {% set online = expand(entity_list)
                  | rejectattr('state','in',['unavailable','unknown'])
                  | map(attribute='entity_id')
                  | list %}

                {% if online | length > 0 %}

                  {% set ref = online[0] %}
                  {% set current = state_attr(ref,'color_temp') | int(min_ct) %}
                  {% set max_ct = [max_ct_user, state_attr(ref,'max_mireds') | int(max_ct_user)] | min %}

                  {% if current <= min_ct + 5 %}
                    {{ max_ct }}
                  {% else %}
                    {{ min_ct }}
                  {% endif %}

                {% else %}
                  {{ max_ct_user }}
                {% endif %}
