blueprint:
  name: ESPhome Button Light Controller (Multi-Light)
  description: >
    Controls multiple lights using an ESPhome button event.
    Single press toggles lights.
    Double press toggles color temperature between 200 mireds and max.
    (Uses the first selected light as the reference for the current state).
  domain: automation

  input:
    button_entity:
      name: Button Entity
      description: The ESPhome event entity (like event.bedroom_button)
      selector:
        entity:
          domain: event
    light_entities:
      name: Light Entities
      description: The lights to control
      selector:
        entity:
          domain: light
          multiple: true

mode: queued
max: 10

trigger:
  - platform: state
    entity_id: !input button_entity
    # FIX: Ignore triggers caused by the device rebooting/connecting
    not_from:
      - "unavailable"
      - "unknown"

action:
  - choose:
      # SINGLE PRESS -> toggle all lights
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: single_press
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_entities

      # DOUBLE PRESS -> toggle color temperature
      - conditions:
          - condition: state
            entity_id: !input button_entity
            attribute: event_type
            state: double_press
        sequence:
          # We import the lights input into a variable named 'lights'
          - variables:
              lights: !input light_entities
          
          - service: light.turn_on
            target:
              entity_id: !input light_entities
            data:
              transition: 1
              color_temp: >
                {# Normalize input to list #}
                {% set entity_list = lights if lights is iterable and lights is not string else [lights] %}

                {# Find first light that actually has color_temp support #}
                {% set ref = namespace(entity=None) %}
                {% for e in entity_list %}
                  {% if state_attr(e,'color_temp') is not none
                        or state_attr(e,'min_mireds') is not none
                        or state_attr(e,'max_mireds') is not none %}
                    {% set ref.entity = e %}
                    {% break %}
                  {% endif %}
                {% endfor %}

                {# If we found a valid reference light #}
                {% if ref.entity %}

                  {% set current = state_attr(ref.entity,'color_temp') | int(default=200) %}
                  {% set min_ct = 200 %}

                  {# Warm target = min(300 , ref.max_mireds) OR 300 if missing #}
                  {% set ref_max = state_attr(ref.entity,'max_mireds') | int(default=300) %}
                  {% set max_ct = [300, ref_max] | min %}

                  {% if current <= min_ct + 5 %}
                    {{ max_ct }}
                  {% else %}
                    {{ min_ct }}
                  {% endif %}

                {% else %}
                  300
                {% endif %}
